### ISSUE TITLE
CRC has changed a lot

### ISSUE THREAD

**Issue by fschiffers** [complight/FisbaReadyBeam#5]
Hi,

in the recent weeks CRC has apparently changed a lot as you can see here: https://pypi.org/project/crc/#history

At least on my Windows-PC I cannot make it work with CRC 4.1 as a lot of the namespaces and function calls have changed.

For now, the solution is to go back to an older version of CRC.

Best,
Florian

**Comment by kaanaksit** [comment]
Hi Florian,

Happy new year!

Perhaps, we can fix the dependency version to be exact for now until we figure out a fix with the latest versions of `CRC.`

So my suggestion is to modify this line:

https://github.com/complight/FisbaReadyBeam/blob/0f9389870f3f07241129a12a0130e851491ddfb7/requirements.txt#L1

Please let me know what you think.

Thanks,
Kaan

**Comment by fschiffers** [comment]
Hi Kaan,

I think that's a good suggestion for now.

Hopefully the CRC package will not change their namespaces too much in the future.

**Comment by kaanaksit** [comment]
I will look into the latest version of  `CRC` at my next availability. So, we should be compatible with the newest version soon. For now, I will hard code the requirement so that the codebase stays usable.
